### ISSUE TITLE
Important contact

### ISSUE THREAD

**Issue by roninhack** [jimmydorry/php-bitcoin#1]
Hi, Can you contact me?

**Comment by jimmydorry** [comment]
What for?

**Comment by roninhack** [comment]
If you are owner this php-bitcoin library; we can earn 5 btc around , my mail : roninhack[at]gmail

**Comment by jimmydorry** [comment]
No thanks. And i’m pretty sure this was just a fork.

**Comment by roninhack** [comment]
do you remember // var_dump(BWWC__MATH_generate_bitcoin_address_from_mpk('b5430fbaeb745611c515f93f044000b37deb2de3411ca1ed274506b472267c44da7ae1f5685c2a74872468d00251700f312ef72ee7a5fcf452a93651fd26e531', 0)); that function use mpk seed or privatekey ?

**Comment by jimmydorry** [comment]
Nope

**Comment by roninhack** [comment]
ok

**Comment by jimmydorry** [comment]
Matyas Danter probably left that test line in there. It’s not particularly useful without the private key.

**Comment by jimmydorry** [comment]
Actually, no, he’s just the ecc library. I dunno where it came from. I’ll remove it for now.

**Comment by roninhack** [comment]
what a coincidence 149W5p6MuvtZ8ZEXF6soBBDY7V3LRUzJJC
